# Use a prelim base image that's just built to only have ever code
FROM obinnamdi/ever:v1.4_prelim_image

# Copy ever code again to reflect code changes
# chown flag is needed to prevent VSCode from breaking edit permissions
COPY ever /ever_training/ever

# Uncomment if you want to update the OptiX version:
# RUN rm -rf /opt/OptiX_7.4
# COPY optix_9/ /opt/OptiX_7.4

RUN source activate ever && \
    rm -rf ever/build && \
    bash install_splinetracer.bash

# Unset LD_LIBRARY_PATH to avoid problems with slangtorch later
ENV LD_LIBRARY_PATH=

# Expose any ports needed for training or viewer
EXPOSE 6009

# By default, just start a shell in the 'ever' environment
CMD ["/bin/bash", "-c", "source activate ever && exec bash"]


# Add user for non-root VSCode DevContainer editing:
# https://code.visualstudio.com/remote/advancedcontainers/add-nonroot-user
# https://askubuntu.com/questions/1042313/ubuntu-command-history-not-available-for-newly-created-user
ARG USERNAME=vscode
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Create the user and add it to sudoers (modified from traditional VSCode Script)
RUN adduser --uid $USER_UID $USERNAME \
    && adduser $USERNAME sudo

# ********************************************************
# * Anything else you want to do like clean up goes here *
# ********************************************************

# [Optional] Set the default user. Omit if you want to keep the default as root.
USER $USERNAME
